introduce dump-signedexchange tool
nyaxt/webpackage pull request #13
Opened 2018-04-09 04:34 UTC by nyaxt

PTAL

2018-04-09 06:22 UTC, hajimehoshi requested changes

2018-04-10 00:51 UTC, nyaxt commented on go/signedexchange/cbor/decoder.go
> +	switch ai {
yes `ai` also used below.

2018-04-10 00:51 UTC, nyaxt commented on go/signedexchange/signedexchange.go
> +	_, _ = w.Write(e.payload)
Done.

2018-04-10 00:51 UTC, nyaxt commented on go/signedexchange/signedexchange.go
> +	fmt.Fprintf(w, "request:\n")
Done.

2018-04-10 00:51 UTC, nyaxt commented on go/signedexchange/cbor/decoder.go
> +		return 0, fmt.Errorf("Expected type %v, got type %v", expected, t)
Done.

2018-04-10 00:52 UTC, nyaxt commented on go/signedexchange/cbor/decoder.go
> +	if _, err := d.r.Read(bs); err != nil {
Good catch!

2018-04-10 00:54 UTC, nyaxt commented on go/signedexchange/signedexchange.go
> +	ValueGet = []byte("GET")
Done.

2018-04-10 00:55 UTC, nyaxt commented on go/signedexchange/signedexchange.go
> +				log.Printf("Failed to parse responseStatus: %q", value)
I'll leave this w/ FIXME comment for now. I think we want some channel to communicate `lint`-like msg that the signed-exchange is ill-formed.

2018-04-10 00:58 UTC, nyaxt commented
OK. PTAL

2018-04-10 08:07 UTC, hajimehoshi requested changes
almost lgtm

2018-04-10 08:07 UTC, hajimehoshi commented on go/signedexchange/mice/mice.go
> +			if _, err := r.Read(proof); err != nil {
`io.ReadFull` ?

2018-04-10 08:07 UTC, hajimehoshi commented on go/signedexchange/mice/mice.go
> +		n, err := r.Read(record)
ditto

2018-04-10 08:07 UTC, hajimehoshi commented on go/signedexchange/mice/mice.go
> +			return fmt.Errorf("Failed to read record: %v", err)
`mice: failed to read ...`

2018-04-10 08:07 UTC, hajimehoshi commented on go/signedexchange/mice/mice.go
> +			return fmt.Errorf("Failed to write record: %v", err)
ditto

2018-04-10 08:07 UTC, hajimehoshi commented on go/signedexchange/signedexchange.go
> +	if _, err := r.Read(cborBytes); err != nil {
`io.ReadFull`

2018-04-10 08:07 UTC, hajimehoshi commented on go/signedexchange/signedexchange.go
> +	if _, err := r.Read(encodedCborLength[:]); err != nil {
`io.ReadFull`

2018-04-11 01:52 UTC, nyaxt commented
PTAL

2018-04-11 02:49 UTC, hajimehoshi approved these changes
lgtm

2018-04-27 18:35 UTC, twifkak commented
@nyaxt Still planning to merge this? I'd like to use it for tests in ampproject/amppackager.

2018-04-27 18:44 UTC, twifkak commented on go/signedexchange/signedexchange.go
>  	payload []byte
Would you mind exporting these fields as part of this change? Or I can open a PR if you prefer.

2018-05-01 06:42 UTC, merged

2018-05-01 06:43 UTC, nyaxt commented
Sorry, I forgot to push the merge btn.